version: '3.3'

services:
  shadowsocks-rust:
    image: teddysun/shadowsocks-rust
    ports:
      - "8379:8379"
      - "8379:8379/udp"
    volumes:
      - ./etc/shadowsocks-rust/config.json:/etc/shadowsocks-rust/config.json
    restart: always
